version: "3.9"

services:
  backend:
    build: .
    container_name: repair_backend
    env_file:
      - .env.docker
    depends_on:
      - mysql
    restart: always
    networks:
      - repair_net

  ecommerce:
    build:
      context: ./frontend
    container_name: repair_ecommerce
    restart: always
    networks:
      - repair_net

  admin:
    build:
      context: ./web
    container_name: repair_admin
    restart: always
    networks:
      - repair_net

  mysql:
    image: mysql:8.0
    container_name: repair_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: repaircrm_db
      MYSQL_USER: repair_user
      MYSQL_PASSWORD: repair_pass
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - repair_net

  nginx:
    image: nginx:latest
    container_name: repair_nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - ecommerce
      - admin
    restart: always
    networks:
      - repair_net

volumes:
  mysql_data:

networks:
  repair_net:
    driver: bridge
